# Generated by Django 4.1.7 on 2023-04-15 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=255)),
                ('TVA', models.CharField(max_length=50)),
                ('nomMarch', models.CharField(max_length=100)),
                ('nomVet', models.CharField(max_length=100)),
                ('telMARCH', models.CharField(max_length=15)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
