# Generated by Django 4.1.7 on 2023-04-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='NomProp',
            field=models.CharField(max_length=255),
        ),
    ]
